/**
 * GENERATED by scripts/build-fonts.py — do not edit.
 *
 * Content-hashed font filenames. public/_headers serves /fonts/* as
 * `immutable` for a year, so the name has to change when the bytes do or
 * nobody ever gets the new file. Re-run the script after changing the
 * subset, the axes, or the source faces.
 */
export const fonts = {
  fraunces: '/fonts/fraunces-e13e4a9f.woff2',
  inter: '/fonts/inter-2a0604d4.woff2',
} as const;

export default fonts;
